include: package:austerity/analysis_options.yaml


analyzer:
  errors:
    avoid_implementing_value_types: ignore
    depend_on_referenced_packages: ignore
    implicit_dynamic_map_literal: ignore
    subtype_of_sealed_class: ignore