name: firestore_fakes
description: A Firestore fake library that gives you control over the data
version: 1.0.2-alpha
repository: https://github.com/MelbourneDeveloper/firestore_fakes

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.4.4
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  uuid: ^3.0.7

dev_dependencies:
  austerity: ^0.0.10-beta
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
